### ISSUE TITLE
Untypable keychain Prompt when signing

### ISSUE THREAD

**Issue by Draawa** [jamf/PPPC-Utility#58]
Hi, I'm using the latest release (1.2.0) and i'm unable to sign my config profile, whenever I chose to save a signed profile, it prompts me with a keychain password and the text fields are broken. It seems i can focus them, it highlights and i can even see the cursor but whenever i try to type in, nothing happens, there's only the anoying error system sound telling that you're typing nowhere.

I tried on different macs, same thing.

Any clue ?

**Comment by macblazer** [comment]
You can click the title bar of the "Enter your keychain password" window to bring it to the front, and then you can type in it.  If I don't click the title bar I get the same behavior of typing into nowhere and hearing error beeps.

We can improve this workflow by waiting for the save dialog to close before doing the work that prompts for keychain access.  The problem is that the system is presenting a modal view (the save dialog) and then needs to display a second modal view (the keychain access prompt) and gets a bit confused as to which one has priority.

Please leave this issue open so we can get a proper code fix in.
